name: langchain-demo-env
channels:
- anaconda
- conda-forge
dependencies:
- python=3.11.7
- pip=23.2.1
- pip:
  - python-dotenv==1.0.1
  # for actual Environment
  - pandas==2.1.4
  - scikit-learn==1.4.0
  - mlflow==2.9.2
  - ipykernel==6.29.0
  - langchain==0.1.12
  - langchain-openai==0.0.8
  - openai==1.13.3
  - google-search-results==2.4.2
  - "black[jupyter]"

  # for later:
  # 